require: rubocop-rspec

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - vendor/**/*

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Metrics/AbcSize:
  Exclude:
    - spec/**/*
