language: ruby
cache: bundler
rvm:
  - 2.1.0
before_script:
  - mysql -e 'create database `berliner-hoefe_test`;'
  - bin/rake db:test:load
script:
  - bin/rspec -c spec
  - bin/rubocop -R
  - bin/haml-lint app/views
  - bin/scss-lint app/assets/stylesheets
