development:
  adapter: mysql2
  encoding: utf8
  database: berliner-hoefe_development
  pool: 5

test:
  adapter: mysql2
  encoding: utf8
  database: berliner-hoefe_test
  pool: 5

production:
  adapter: mysql2
  encoding: utf8
  database: geni_berliner-hoefe
  pool: 5
  username: geni
  password: JejEgpaugjigok
  socket: /var/lib/mysql/mysql.sock
