development:
  adapter: mysql2
  encoding: utf8
  database: berliner-hoefe_development

test:
  adapter: mysql2
  encoding: utf8
  database: berliner-hoefe_test
  <%= "username: travis" if ENV['TRAVIS'] %>

production:
  adapter: mysql2
  encoding: utf8
  database: geni_berliner-hoefe
  username: geni
  password: JejEgpaugjigok
  socket: /var/lib/mysql/mysql.sock
